[package]
name = "esp-hal-rmt-onewire"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-futures = { version = "0.1.1" }
esp-hal = { version = "0.17.0", features = [ "esp32c3", "embassy", "async" ] }

